package dsw.GeRuMap.app.gui.messagegenerator;

public enum Type {
    BRISANJE_PROJECT_EXPLORERA_ERROR,
    DODAVANJE_DETETA_ELEMENTU_ERROR,
    PRAZNO_IME_PROJEKTA_ERROR,

    PRAZNO_IME_PROJEKTA_I_AUTORA,
    PRAZNO_IME_AUTORA_ERROR;

}
